apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cert-sync.configMapName" . }}
  labels:
    {{- include "cert-sync.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- with .Values.config.aws }}
    aws:
      region:
        - {{ required "config.aws.region required if using aws destination"  .region }}
      {{- with .credentials }}
      credentials:
        access_key: {{ required "config.aws.credentials.access_key required if not using IAM Role" .access_key }}
        secret_key: {{ required "config.aws.credentials.secret_key required if not using IAM Role" .secret_key }}
      {{- end }}
      {{- range $lb := .load_balancers }}
      load_balancers:
        - {{ $lb }}
      {{- end }}
    {{- end }}
