apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cert-sync.clusterRoleBindingName" . }}
  labels: {{ include "cert-sync.labels" . | nindent 4 }}
subjects:
  - kind: User
    name: {{ include "cert-sync.serviceAccountName" . }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ include "cert-sync.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
