name: Docker application packaging

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Retrieve Rust related cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-cert-sync-release
      - name: Build application in release mode
        run:  cargo build --release
      - name: Upload application binary
        uses: actions/upload-artifact@v2
        with:
          name: application
          path: target/release/cert-sync

  publish:
    name: Package and publish
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Extract Tag from Ref
        id: get-tag
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download application binary
        uses: actions/download-artifact@v2
        with:
          name: application
          path: target/release
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.io/wykiio/cert-sync:${{ steps.get-tag.outputs.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
